"""
Generate pre-patched openclaw.json for offline Ollama use.
Phase 9: ctx cap at 8192 for local models, kimi-k2.5 added, qwen3 removed.
"""
import json
import subprocess
from pathlib import Path

OPENCLAW_DIR  = Path.home() / ".openclaw"
CONFIG_PATH   = OPENCLAW_DIR / "openclaw.json"
AUTH_FIX_PATH = OPENCLAW_DIR / "agents" / "main" / "agent" / "auth-profiles.json"

# Four models. Nothing else. No exceptions.
# qwen3 excluded — Ollama bug #14745 (prints tool calls instead of executing)
GOOD_MODELS = {
    "qwen2.5:1.5b":    {"ctx": 4096,  "maxOutput": 2048, "tier": "basic"},
    "qwen2.5:3b":      {"ctx": 8192,  "maxOutput": 4096, "tier": "standard"},
    "qwen2.5:7b":      {"ctx": 8192,  "maxOutput": 4096, "tier": "full"},
    "kimi-k2.5:cloud": {"ctx": 32768, "maxOutput": 8192, "tier": "openclaw"},
}

CTX_CAP = 8192  # hard cap for local models — prevents 262k OOM (qwen3 bug)


def gen_config(model: str = "qwen2.5:7b") -> dict:
    """
    Pre-patched openclaw.json for offline Ollama.
    Critical: api must be 'openai-completions' (not 'openai-responses').
    baseUrl must include /v1.
    """
    m = GOOD_MODELS.get(model, {"ctx": CTX_CAP, "maxOutput": 4096})
    ctx = min(m["ctx"], CTX_CAP) if "cloud" not in model else m["ctx"]
    return {
        "models": {
            "providers": {
                "ollama": {
                    "baseUrl": "http://127.0.0.1:11434/v1",
                    "apiKey":  "ollama-local",
                    "api":     "openai-completions",
                    "models":  [{
                        "id":              model,
                        "name":            model,
                        "contextWindow":   ctx,
                        "maxOutput":       m["maxOutput"],
                        "inputCostPer1M":  0,
                        "outputCostPer1M": 0,
                        "capabilities":    ["tools", "streaming"],
                    }]
                }
            }
        },
        "agents": {
            "defaults": {
                "model": {"primary": f"ollama/{model}"}
            }
        },
        "cloud":   {"enabled": False, "fallback": False},
        "network": {
            "mode":                "offline",
            "allow_local_network": True,
            "allow_internet":      False,
        },
        "skills": {
            "web-browser":  {"offline_behavior": "disable"},
            "file-manager": {"offline_behavior": "normal"},
        },
        "_clawos": "Generated by ClawOS — github.com/xbrxr03/clawos",
    }


def apply_auth_fix() -> Path:
    """Fix Linux issue #22055 — 'No API key found for provider ollama'."""
    AUTH_FIX_PATH.parent.mkdir(parents=True, exist_ok=True)
    AUTH_FIX_PATH.write_text(json.dumps({
        "ollama:local": {"type": "token", "provider": "ollama", "token": "ollama-local"},
        "lastGood":     {"ollama": "ollama:local"},
    }, indent=2))
    return AUTH_FIX_PATH


def write_config(model: str = "qwen2.5:7b") -> Path:
    OPENCLAW_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(json.dumps(gen_config(model), indent=2))
    return CONFIG_PATH


def detect_best_model() -> str:
    """Pick best available Ollama model that supports OpenClaw tool calling."""
    try:
        r = subprocess.run(["ollama", "list"], capture_output=True, text=True, timeout=5)
        output = r.stdout.lower()
        for model in ["qwen2.5:7b", "qwen2.5:3b", "qwen2.5:1.5b"]:
            if model.split(":")[0] in output:
                return model
    except Exception:
        pass
    return "qwen2.5:7b"
